services:
  mission-service:
    build: ../backend/mission-service
    ports:
      - "3000:3000"
    volumes:
      - ../backend/mission-service:/usr/src/app
    networks:
      - questify-network
    depends_on:
      - mongo

  character-service:
    build: ../backend/character-service
    ports:
      - "5000:5000"
    volumes:
      - ../backend/character-service:/usr/src/app
    networks:
      - questify-network
    depends_on:
      - postgres

  guild-service:
    build: ../backend/guild-service
    ports:
      - "8081:8080"
    volumes:
      - ../backend/guild-service:/usr/src/app
    networks:
      - questify-network
    depends_on:
      - mongo

  reward-service:
    build: ../backend/reward-service
    ports:
      - "3001:3000"
    volumes:
      - ../backend/reward-service:/usr/src/app
    networks:
      - questify-network
    depends_on:
      - mongo

  gamification-service:
    build: ../backend/gamification-service
    ports:
      - "8082:8080"
    volumes:
      - ../backend/gamification-service:/usr/src/app
    networks:
      - questify-network
    depends_on:
      - mongo

  user-service:
    build: ../backend/user-service
    ports:
      - "8085:8080"   
    volumes:
      - ../backend/user-service:/app  
    networks:
      - questify-network
    depends_on:
      - postgres


  frontend:
    build: ../frontend
    ports:
      - "3002:3000"
    volumes:
      - ../frontend:/usr/src/app
    networks:
      - questify-network

  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: INSIDE://localhost:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    networks:
      - questify-network
    depends_on:
      - zookeeper

  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
    networks:
      - questify-network

  mongo:
    image: mongo
    ports:
      - "27017:27017"
    networks:
      - questify-network

  postgres:
    image: postgres
    environment:
      POSTGRES_USER: questify_user
      POSTGRES_PASSWORD: questify_password
      POSTGRES_DB: questify_db
    ports:
      - "5432:5432"
    networks:
      - questify-network

networks:
  questify-network:
    driver: bridge
